"""WordPress Runtime Observability simulator.

This module produces a correlated, layered runtime snapshot for the
``/monitor/wp-runtime`` endpoints. It simulates a production WordPress stack
running on OpenLiteSpeed + LSPHP + Redis + MariaDB and exposes the four
observability layers described in the PRD:

* L1 - Metrics (raw signals from every layer)
* L2 - Correlation (request lifecycle trace, cross-layer causality)
* L3 - AI Analysis (root-cause style explanation of score components)
* L4 - Auto Optimization (one-click remediation actions)

The data is generated by a stateful simulator so that consecutive polls show a
coherent, slowly evolving picture rather than random noise, and so that the
"auto optimization" actions have a visible, persistent effect.
"""

from __future__ import annotations

import math
import os
import json
import random
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

# Real stack paths (OpenLiteSpeed tech base)
LSWS_HOME = "/usr/local/lsws"
OLS_PHP_BIN = os.path.join(LSWS_HOME, "lsphp83", "bin", "lsphp")

# ---------------------------------------------------------------------------
# Tunable baseline configuration for the simulated stack
# ---------------------------------------------------------------------------

BASELINE = {
    "qps": 42.0,
    "p95_ms": 210.0,
    "p99_ms": 460.0,
    "avg_ms": 120.0,
    "cache_hit": 98.6,            # overall LSCache hit rate (%)
    "redis_hit": 96.5,
    "php_avg_ms": 38.0,
    "worker_total": 8,
    "worker_conns": 800,          # max connections per worker pool
    "db_qps": 230.0,
    "db_avg_ms": 11.5,
    "opcache_mb": 64.0,           # opcache used
    "opcache_total_mb": 128.0,
}

# History ring buffers keep time-series charts consistent across polls.
_HISTORY_LEN = 60


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def _walk(value: float, pct: float, lo: float, hi: float) -> float:
    """Random-walk ``value`` by at most ``pct`` of its magnitude, clamped."""
    delta = value * pct * (random.random() * 2 - 1)
    return _clamp(value + delta, lo, hi)


# ---------------------------------------------------------------------------
# Simulator
# ---------------------------------------------------------------------------


class WPRuntimeSimulator:
    """Stateful simulator that generates a WordPress runtime snapshot."""

    def __init__(self) -> None:
        self.state = dict(BASELINE)
        self.qps_history: List[float] = []
        self.p95_history: List[float] = []
        self.ttfb_history: List[float] = []
        self.cache_history: List[float] = []
        self.db_history: List[float] = []
        self._seed_history()
        self.applied_optimizations: Dict[str, Any] = {}
        self.timeline: List[Dict[str, str]] = self._seed_timeline()
        self._tick = 0

    # --- history seeding -------------------------------------------------

    def _seed_history(self) -> None:
        for _ in range(_HISTORY_LEN):
            self.qps_history.append(_walk(self.state["qps"], 0.08, 5, 200))
            self.p95_history.append(_walk(self.state["p95_ms"], 0.06, 80, 1200))
            self.ttfb_history.append(_walk(self.state["avg_ms"] * 0.8, 0.06, 30, 900))
            self.cache_history.append(_walk(self.state["cache_hit"], 0.01, 80, 100))
            self.db_history.append(_walk(self.state["db_qps"], 0.06, 20, 800))

    def _seed_timeline(self) -> List[Dict[str, str]]:
        now = datetime.now(timezone.utc)
        events = [
            ("10:02", "deploy", "WordPress 核心升级 6.6.2 → 6.6.3 完成"),
            ("11:15", "cache", "LSCache 缓存命中率突破 98%"),
            ("12:40", "warning", "高峰期 worker 连接池占用 92%，触发排队"),
            ("13:05", "plugin", "WooCommerce 更新至 9.3.1"),
            ("13:50", "db", "wp_options 慢查询告警，autoload 数据 1.2MB"),
            ("14:20", "optimize", "已执行 opcache 内存扩容至 128MB"),
        ]
        out = []
        for hm, kind, text in events:
            ts = now.replace(hour=int(hm.split(":")[0]), minute=int(hm.split(":")[1]))
            out.append({"time": ts.strftime("%H:%M"), "type": kind, "text": text})
        return out

    # --- public API ------------------------------------------------------

    def snapshot(self, db=None) -> Dict[str, Any]:
        self._tick += 1
        self._evolve()
        real = {
            "ols": self._ols_status(),
            "php": self._php_status(),
            "mariadb": self._mariadb_status(db),
        }
        return self._build(real)

    def optimize(self, action: str) -> Dict[str, Any]:
        return self._apply_optimization(action)

    # --- internals -------------------------------------------------------

    def _evolve(self) -> None:
        s = self.state
        # smooth random walks around baseline (optimizations shift baselines)
        s["qps"] = _walk(s["qps"], 0.05, 5, 220)
        s["p95_ms"] = _walk(s["p95_ms"], 0.04, 80, 1500)
        s["p99_ms"] = _walk(s["p99_ms"], 0.04, 120, 3000)
        s["avg_ms"] = _walk(s["avg_ms"], 0.04, 40, 900)
        s["cache_hit"] = _walk(s["cache_hit"], 0.01, 70, 100)
        s["redis_hit"] = _walk(s["redis_hit"], 0.01, 60, 100)
        s["php_avg_ms"] = _walk(s["php_avg_ms"], 0.05, 10, 600)
        s["db_qps"] = _walk(s["db_qps"], 0.05, 20, 900)
        s["db_avg_ms"] = _walk(s["db_avg_ms"], 0.04, 4, 200)

        # occasionally inject an event into the timeline
        if random.random() < 0.08 and self._tick % 3 == 0:
            self._add_event()

        # push history
        self.qps_history.append(s["qps"])
        self.p95_history.append(s["p95_ms"])
        self.ttfb_history.append(s["avg_ms"] * 0.8)
        self.cache_history.append(s["cache_hit"])
        self.db_history.append(s["db_qps"])
        for buf in (
            self.qps_history,
            self.p95_history,
            self.ttfb_history,
            self.cache_history,
            self.db_history,
        ):
            if len(buf) > _HISTORY_LEN:
                del buf[0]

    def _add_event(self) -> None:
        pool = [
            ("cache", "缓存预热完成，命中率回升"),
            ("db", "检测到一次慢查询 > 500ms"),
            ("plugin", "RankMath SEO 计划任务执行"),
            ("warning", "PHP worker 内存接近上限"),
            ("worker", "worker 进程平滑重启"),
            ("network", "TLS 握手耗时小幅上升"),
        ]
        kind, text = random.choice(pool)
        now = datetime.now(timezone.utc)
        self.timeline.append({"time": now.strftime("%H:%M"), "type": kind, "text": text})
        if len(self.timeline) > 40:
            del self.timeline[0]

    def _series(self, buf: List[float]) -> List[Dict[str, Any]]:
        base = int(time.time()) - len(buf)
        return [{"t": base + i, "v": round(v, 2)} for i, v in enumerate(buf)]

    # --- real data collectors -----------------------------------------

    def _ols_status(self) -> Dict[str, Any]:
        """真实 OpenLiteSpeed 状态（进程 / 版本）。"""
        out: Dict[str, Any] = {"available": False, "running": False, "version": None, "error": None}
        try:
            if not os.path.exists(os.path.join(LSWS_HOME, "bin", "lswsctrl")):
                out["error"] = "OLS 未安装"
                return out
            res = subprocess.run(
                f"{LSWS_HOME}/bin/lswsctrl status", shell=True, capture_output=True, text=True, timeout=8
            )
            out["running"] = "is running" in res.stdout
            v = subprocess.run(
                f"{LSWS_HOME}/bin/lshttpd -v", shell=True, capture_output=True, text=True, timeout=8
            )
            if v.returncode == 0 and v.stdout:
                out["version"] = v.stdout.splitlines()[0].strip()
            out["available"] = True
        except Exception as e:  # pragma: no cover
            out["error"] = str(e)
        return out

    def _php_status(self) -> Dict[str, Any]:
        """真实 PHP / OPcache 状态。"""
        out: Dict[str, Any] = {
            "available": False, "version": None, "opcache_enabled": None,
            "opcache_hit_rate": None, "opcache_used_mb": None,
            "opcache_total_mb": None, "error": None,
        }
        php_bin = OLS_PHP_BIN if os.path.exists(OLS_PHP_BIN) else None
        if php_bin is None:
            try:
                from backend.utils.php_utils import find_php_executable
                php_bin = find_php_executable()
            except Exception:
                php_bin = None
        if not php_bin:
            out["error"] = "未找到 PHP 可执行文件"
            return out
        try:
            v = subprocess.run([php_bin, "-v"], capture_output=True, text=True, timeout=8)
            if v.returncode == 0 and v.stdout:
                parts = v.stdout.splitlines()[0].split(" ")
                out["version"] = parts[1] if len(parts) >= 2 else None
            code = (
                "<?php $s=@opcache_get_status(false);"
                "if($s&&!empty($s['opcache_statistics'])){"
                "echo json_encode(['ok'=>true,"
                "'hit_rate'=>round($s['opcache_statistics']['opcache_hit_rate']??0,2),"
                "'used_mb'=>round($s['memory_usage']['used_memory']/1048576,1),"
                "'total_mb'=>round(($s['memory_usage']['used_memory']+$s['memory_usage']['free_memory'])/1048576,1)]);"
                "}else{echo json_encode(['ok'=>false]);}"
            )
            r = subprocess.run([php_bin, "-r", code], capture_output=True, text=True, timeout=8)
            try:
                j = json.loads(r.stdout.strip())
                out["opcache_enabled"] = bool(j.get("ok"))
                if j.get("ok"):
                    out["opcache_hit_rate"] = j.get("hit_rate")
                    out["opcache_used_mb"] = j.get("used_mb")
                    out["opcache_total_mb"] = j.get("total_mb")
            except Exception:
                out["opcache_enabled"] = False
            out["available"] = True
        except Exception as e:  # pragma: no cover
            out["error"] = str(e)
        return out

    def _mariadb_status(self, db) -> Dict[str, Any]:
        """真实 MariaDB 全局状态（连接 / 慢查询 / QPS）。"""
        out: Dict[str, Any] = {"available": False, "error": None}
        if db is None:
            out["error"] = "无数据库会话"
            return out
        try:
            from backend.models.site import Site as SiteModel, SharedDatabase as SharedDatabaseModel
            shared = db.query(SharedDatabaseModel).filter(SharedDatabaseModel.status == "active").first()
            if not shared:
                shared = db.query(SharedDatabaseModel).first()
            if not shared:
                out["error"] = "未找到共享数据库凭据"
                return out
            import mysql.connector
            conn = mysql.connector.connect(
                host=shared.db_host, port=shared.db_port,
                user=shared.db_user, password=shared.db_password, connect_timeout=5,
            )
            cur = conn.cursor()
            cur.execute(
                "SHOW GLOBAL STATUS WHERE Variable_name IN "
                "('Threads_connected','Connections','Queries','Slow_queries','Uptime',"
                "'Aborted_connects','Max_used_connections')"
            )
            st = {k: int(v) for k, v in cur.fetchall()}
            cur.execute("SHOW VARIABLES WHERE Variable_name IN ('max_connections')")
            vars_ = {k: int(v) for k, v in cur.fetchall()}
            cur.close()
            conn.close()
            uptime = max(1, st.get("Uptime", 1))
            qps = round(st.get("Queries", 0) / uptime, 1)
            slow = st.get("Slow_queries", 0)
            slow_rate = round(slow / max(1, st.get("Queries", 1)) * 100, 3)
            max_conn = vars_.get("max_connections", 151)
            threads = st.get("Threads_connected", 0)
            conn_util = round(threads / max(1, max_conn) * 100, 1)
            out.update({
                "available": True, "running": True,
                "threads_connected": threads, "max_connections": max_conn,
                "connection_util": conn_util, "qps": qps,
                "queries": st.get("Queries", 0), "slow_queries": slow,
                "slow_rate": slow_rate, "uptime": uptime,
                "max_used_connections": st.get("Max_used_connections", 0),
                "aborted_connects": st.get("Aborted_connects", 0),
            })
        except Exception as e:  # pragma: no cover
            out["error"] = str(e)
        return out

    # --- snapshot builder ------------------------------------------------

    def _build(self, real: Dict[str, Any]) -> Dict[str, Any]:
        s = self.state
        score = self._score(real)
        return {
            "generated_at": _now(),
            "score": score,
            "request": self._request(score),
            "cache": self._cache(),
            "php": self._php(real),
            "worker": self._worker(),
            "database": self._database(real),
            "redis": self._redis(),
            "wordpress": self._wordpress(),
            "storage": self._storage(),
            "network": self._network(),
            "errors": self._errors(),
            "timeline": self.timeline[-20:],
            "ai_analysis": self._ai_analysis(score),
            "optimizations": self._optimization_list(),
            "real_signals": {
                "ols": real.get("ols"),
                "php": real.get("php"),
                "mariadb": real.get("mariadb"),
            },
        }

    # -- L4 score ---------------------------------------------------------

    def _score(self, real: Dict[str, Any]) -> Dict[str, Any]:
        s = self.state
        real = real or {}
        # each component score is derived from a real-ish signal
        cache_score = int(_clamp((s["cache_hit"] - 70) / 30 * 100, 0, 100))
        redis_score = int(_clamp((s["redis_hit"] - 50) / 50 * 100, 0, 100))
        worker = self._worker()
        worker_score = int(_clamp(
            100 - max(0, worker["queue"] - 80) / 8 - max(0, worker["utilization"] - 75) / 5,
            0, 100,
        ))
        wp_score = int(_clamp(100 - self._wordpress()["plugin_total_ms"] / 30, 0, 100))
        storage_score = int(_clamp(100 - self._storage()["total_gb"] / 5, 0, 100))

        # ---- web_server: 真实 OLS 状态 ----
        ols = real.get("ols") or {}
        if ols.get("available") and ols.get("running"):
            web_score = 100
        elif ols.get("available") and not ols.get("running"):
            web_score = 0
        else:
            web_score = int(_clamp(100 - max(0, s["p95_ms"] - 150) / 12, 0, 100))

        # ---- php_runtime: 真实 OPcache 命中率 ----
        php_real = real.get("php") or {}
        if php_real.get("opcache_enabled") and php_real.get("opcache_hit_rate") is not None:
            php_score = int(_clamp(php_real["opcache_hit_rate"], 0, 100))
        elif php_real.get("available") and not php_real.get("opcache_enabled"):
            php_score = int(_clamp(100 - max(0, s["php_avg_ms"] - 30) / 8, 0, 100)) - 10
        else:
            php_score = int(_clamp(100 - max(0, s["php_avg_ms"] - 30) / 8, 0, 100))

        # ---- database: 真实 MariaDB 慢查询率 / 连接利用率 ----
        db_real = real.get("mariadb") or {}
        if db_real.get("available"):
            db_score = int(_clamp(
                100 - db_real.get("slow_rate", 0) * 120 - max(0, db_real.get("connection_util", 0) - 70) / 2,
                0, 100,
            ))
        else:
            db_score = int(_clamp(100 - max(0, s["db_avg_ms"] - 10) / 6, 0, 100))

        components = {
            "web_server": {"label": "Web Server", "score": web_score, "source": "real" if ols.get("available") else "sim"},
            "cache": {"label": "Cache Layer", "score": cache_score, "source": "sim"},
            "php_runtime": {"label": "PHP Runtime", "score": php_score, "source": "real" if php_real.get("available") else "sim"},
            "worker": {"label": "Worker Pool", "score": worker_score, "source": "sim"},
            "database": {"label": "Database", "score": db_score, "source": "real" if db_real.get("available") else "sim"},
            "redis": {"label": "Redis", "score": redis_score, "source": "sim"},
            "wordpress": {"label": "WordPress Core", "score": wp_score, "source": "sim"},
            "storage": {"label": "Storage", "score": storage_score, "source": "sim"},
        }
        total = int(round(sum(c["score"] for c in components.values()) / len(components)))
        grade = "A" if total >= 90 else "B" if total >= 80 else "C" if total >= 70 else "D"
        return {
            "total": total,
            "grade": grade,
            "components": components,
        }

    # -- L1 request -------------------------------------------------------

    def _request(self, score: Dict[str, Any]) -> Dict[str, Any]:
        s = self.state
        errors_500 = int(random.randint(2, 18))
        errors_404 = int(random.randint(120, 360))
        errors_403 = int(random.randint(2, 20))
        total_err = errors_500 + errors_404 + errors_403
        return {
            "qps": round(s["qps"], 1),
            "total_today": 328_400 + int(s["qps"] * 60),
            "p95": round(s["p95_ms"], 0),
            "p99": round(s["p99_ms"], 0),
            "avg": round(s["avg_ms"], 0),
            "errors": {"500": errors_500, "404": errors_404, "403": errors_403},
            "error_rate": round(total_err / max(1, s["qps"] * 60) * 100, 2),
            "status_series": self._series([s["qps"]] * _HISTORY_LEN),
            "qps_series": self._series(self.qps_history),
            "p95_series": self._series(self.p95_history),
            "ttfb_series": self._series(self.ttfb_history),
            "top_urls": [
                {"path": "/", "pct": 34},
                {"path": "/shop/", "pct": 18},
                {"path": "/product/xxx/", "pct": 12},
                {"path": "/cart/", "pct": 9},
                {"path": "/wp-json/wc/v3/products", "pct": 7},
                {"path": "/blog/", "pct": 5},
            ],
        }

    # -- L1 cache ---------------------------------------------------------

    def _cache(self) -> Dict[str, Any]:
        s = self.state
        overall = s["cache_hit"]
        return {
            "overall_hit": round(overall, 2),
            "public": round(_clamp(overall + 0.3, 0, 100), 2),
            "private": round(_walk(86.0, 0.03, 40, 100), 2),
            "browser": round(_walk(91.0, 0.03, 50, 100), 2),
            "redis": round(s["redis_hit"], 2),
            "guest_mode": False,
            "esi": False,
            "miss_reason": "未命中主要来自登录用户后台 (admin-ajax) 与购物车动态接口",
            "ai_tip": "建议为未缓存的接口启用 ESI 或 Object Cache，可将命中率再提升 2-3 个百分点。",
            "series": self._series(self.cache_history),
        }

    # -- L1 php -----------------------------------------------------------

    def _php(self, real: Dict[str, Any] = None) -> Dict[str, Any]:
        s = self.state
        real = real or {}
        php_real = real.get("php") or {}
        version = php_real.get("version") or "8.3"
        opcache = {
            "used": round(s["opcache_mb"], 1),
            "total": round(s["opcache_total_mb"], 1),
            "hit_rate": round(_walk(97.5, 0.01, 80, 100), 2),
        }
        if php_real.get("opcache_used_mb") is not None:
            opcache["used"] = php_real["opcache_used_mb"]
        if php_real.get("opcache_total_mb") is not None:
            opcache["total"] = php_real["opcache_total_mb"]
        if php_real.get("opcache_hit_rate") is not None:
            opcache["hit_rate"] = php_real["opcache_hit_rate"]
        return {
            "avg_time": round(s["php_avg_ms"], 1),
            "version": version,
            "opcache_enabled": php_real.get("opcache_enabled"),
            "slow_scripts": [
                {"script": "wp-admin/admin-ajax.php", "ms": round(_walk(820, 0.1, 200, 2000), 0)},
                {"script": "wp-content/plugins/woocommerce/includes/class-wc-ajax.php", "ms": round(_walk(540, 0.1, 100, 1500), 0)},
                {"script": "wp-content/themes/astra/functions.php", "ms": round(_walk(120, 0.1, 20, 600), 0)},
                {"script": "wp-includes/load.php", "ms": round(_walk(60, 0.1, 10, 300), 0)},
            ],
            "errors": {
                "fatal": random.randint(0, 3),
                "warning": random.randint(8, 25),
                "notice": random.randint(60, 180),
                "deprecated": random.randint(2, 12),
            },
            "opcache": opcache,
        }

    # -- L1 worker --------------------------------------------------------

    def _worker(self) -> Dict[str, Any]:
        s = self.state
        total = int(s["worker_total"])
        busy = random.randint(2, max(2, total - 1))
        idle = total - busy
        queue = int(_walk(78, 0.15, 0, 400))
        return {
            "total": total,
            "busy": list(range(busy)),
            "idle": list(range(idle)),
            "queue": queue,
            "restarts": random.randint(0, 4),
            "memory_mb": round(_walk(256, 0.05, 64, 1024), 0),
            "max_conns": int(s["worker_conns"]),
            "utilization": round(busy / total * 100, 0),
            "ai_tip": "高峰期连接池占用偏高，建议将 worker 数量由 %d 提升至 %d 并开启 keep-alive 复用。"
            % (total, min(20, total + 4)),
        }

    # -- L1 database ------------------------------------------------------

    def _database(self, real: Dict[str, Any] = None) -> Dict[str, Any]:
        s = self.state
        real = real or {}
        db_real = real.get("mariadb") or {}
        qps = db_real.get("qps", round(s["db_qps"], 1)) if db_real.get("available") else round(s["db_qps"], 1)
        connections = db_real.get("threads_connected", random.randint(30, 70)) if db_real.get("available") else random.randint(30, 70)
        max_connections = db_real.get("max_connections", 151) if db_real.get("available") else 151
        slow_queries = db_real.get("slow_queries", random.randint(12, 60)) if db_real.get("available") else random.randint(12, 60)
        avg_query_ms = round(s["db_avg_ms"], 2)
        if db_real.get("available") and db_real.get("qps") is not None:
            # 真实 QPS 越高，典型查询耗时估算越低（粗粒度关联）
            avg_query_ms = round(_clamp(1000.0 / max(1, db_real["qps"]), 1, 200), 2)
        return {
            "qps": qps,
            "avg_query_ms": avg_query_ms,
            "slow_queries": slow_queries,
            "locks": random.randint(0, 6),
            "deadlocks": random.randint(0, 2),
            "connections": connections,
            "max_connections": max_connections,
            "connection_util": db_real.get("connection_util"),
            "top_tables": [
                {"table": "wp_postmeta", "ms": round(_walk(820, 0.1, 200, 2000), 0)},
                {"table": "wp_options", "ms": round(_walk(680, 0.1, 150, 1800), 0)},
                {"table": "wp_posts", "ms": round(_walk(420, 0.1, 100, 1200), 0)},
                {"table": "wp_wc_orders", "ms": round(_walk(310, 0.1, 80, 900), 0)},
            ],
            "top_sql": [
                {"sql": "SELECT autoload FROM wp_options WHERE autoload='yes'", "ms": 680, "plugin": "WordPress Core"},
                {"sql": "SELECT meta_value FROM wp_postmeta WHERE post_id=?", "ms": 540, "plugin": "WooCommerce"},
                {"sql": "SELECT * FROM wp_posts WHERE post_type='product'", "ms": 420, "plugin": "WooCommerce"},
            ],
            "series": self._series(self.db_history),
        }

    # -- L1 redis ---------------------------------------------------------

    def _redis(self) -> Dict[str, Any]:
        s = self.state
        return {
            "hit": round(s["redis_hit"], 2),
            "miss": round(100 - s["redis_hit"], 2),
            "memory_mb": round(_walk(156, 0.05, 20, 1024), 1),
            "evicted": random.randint(0, 12),
            "latency_ms": round(_walk(0.42, 0.1, 0.1, 5), 2),
            "keys": random.randint(3800, 5200),
            "ops_per_sec": round(_walk(1200, 0.1, 100, 5000), 0),
            "top_prefix": [
                {"prefix": "woocommerce", "pct": 38},
                {"prefix": "wp_options", "pct": 22},
                {"prefix": "rankmath", "pct": 14},
                {"prefix": "session", "pct": 10},
                {"prefix": "transient", "pct": 8},
            ],
            "ai_tip": "命中率健康，建议为 session 前缀设置独立 TTL 避免长期驻留占用内存。",
        }

    # -- L1 wordpress -----------------------------------------------------

    def _wordpress(self) -> Dict[str, Any]:
        plugin_time = [
            {"name": "WooCommerce", "ms": round(_walk(120, 0.1, 40, 400), 0), "pct": 48},
            {"name": "RankMath SEO", "ms": round(_walk(34, 0.1, 10, 150), 0), "pct": 14},
            {"name": "WP Rocket", "ms": round(_walk(26, 0.1, 5, 120), 0), "pct": 10},
            {"name": "Elementor", "ms": round(_walk(22, 0.1, 5, 120), 0), "pct": 9},
            {"name": "Query Monitor", "ms": round(_walk(12, 0.1, 2, 60), 0), "pct": 5},
        ]
        plugin_total_ms = sum(p["ms"] for p in plugin_time)
        return {
            "version": "6.6.3",
            "plugin_time": plugin_time,
            "plugin_total_ms": plugin_total_ms,
            "theme_time": [
                {"name": "Astra", "ms": round(_walk(18, 0.1, 5, 80), 0), "pct": 62},
                {"name": "Astra Child", "ms": round(_walk(11, 0.1, 2, 60), 0), "pct": 38},
            ],
            "hook_time": [
                {"hook": "init", "ms": round(_walk(20, 0.1, 5, 80), 0)},
                {"hook": "wp_loaded", "ms": round(_walk(14, 0.1, 3, 60), 0)},
                {"hook": "template_redirect", "ms": round(_walk(8, 0.1, 2, 40), 0)},
                {"hook": "shutdown", "ms": round(_walk(6, 0.1, 1, 30), 0)},
            ],
            "cron": {
                "pending": random.randint(8, 24),
                "last_run": _now(),
                "longest_ms": round(_walk(420, 0.1, 100, 1500), 0),
            },
            "rest_api": {
                "qps": round(_walk(14, 0.1, 2, 80), 1),
                "avg_ms": round(_walk(95, 0.1, 20, 400), 0),
            },
            "heartbeat": {
                "enabled": True,
                "interval_s": 60,
                "cost": round(_walk(6, 0.1, 1, 30), 1),
            },
        }

    # -- L1 storage -------------------------------------------------------

    def _storage(self) -> Dict[str, Any]:
        return {
            "uploads_gb": 30.2,
            "cache_gb": 12.4,
            "logs_gb": 5.1,
            "backups_gb": 8.3,
            "total_gb": 56.0,
            "disk_total_gb": 200.0,
            "top_folders": [
                {"path": "wp-content/uploads", "gb": 18.2},
                {"path": "wp-content/cache", "gb": 12.4},
                {"path": "wp-content/backup", "gb": 8.3},
                {"path": "wp-content/logs", "gb": 5.1},
            ],
        }

    # -- L1 network -------------------------------------------------------

    def _network(self) -> Dict[str, Any]:
        return {
            "bandwidth_in_mbps": round(_walk(120, 0.1, 10, 1000), 1),
            "bandwidth_out_mbps": round(_walk(340, 0.1, 20, 2000), 1),
            "tls_handshake_ms": round(_walk(28, 0.1, 10, 120), 1),
            "http3_pct": round(_walk(38, 0.05, 0, 100), 1),
            "http2_pct": round(_walk(58, 0.05, 0, 100), 1),
            "conn_per_ip": round(_walk(4.2, 0.1, 1, 30), 1),
            "series_in": self._series([120] * _HISTORY_LEN),
            "series_out": self._series([340] * _HISTORY_LEN),
        }

    # -- L2 errors / issues ----------------------------------------------

    def _errors(self) -> Dict[str, Any]:
        s = self.state
        critical = []
        warning = []
        info = []
        if s["cache_hit"] < 95:
            warning.append("LSCache 命中率低于 95%，存在可缓存请求未命中")
        if self._php()["avg_time"] > 120:
            warning.append("PHP 平均执行时间偏高，疑似慢插件或慢查询")
        if self._worker()["queue"] > 200:
            critical.append("Worker 连接池排队严重，请求出现排队等待")
        if self._database()["slow_queries"] > 40:
            warning.append("数据库慢查询数量偏多，建议添加索引")
        if self._redis()["hit"] < 90:
            info.append("Redis 命中率一般，可增大内存上限或调整 TTL")
        warning.append("admin-ajax.php 占用大量 worker，建议限制心跳频率")
        info.append("wp_options 表 autoload 数据较大，建议清理")
        return {
            "critical": [{"level": "critical", "text": t} for t in critical],
            "warning": [{"level": "warning", "text": t} for t in warning],
            "info": [{"level": "info", "text": t} for t in info],
        }

    # -- L3 AI analysis ---------------------------------------------------

    def _ai_analysis(self, score: Dict[str, Any]) -> Dict[str, Any]:
        items = []
        comps = score["components"]
        for key, c in comps.items():
            if c["score"] >= 90:
                status = "健康"
                cause = "指标处于优秀区间，无需干预。"
                suggestion = "保持当前配置即可。"
            elif c["score"] >= 80:
                status = "良好"
                cause = "存在轻微波动，不影响整体体验。"
                suggestion = "可在低峰期微调参数。"
            elif c["score"] >= 70:
                status = "需关注"
                cause = "部分请求超出预期延迟，存在隐患。"
                suggestion = "建议执行对应优化项。"
            else:
                status = "异常"
                cause = "关键指标劣化明显，已影响用户体验。"
                suggestion = "建议立即执行自动优化。"
            items.append({
                "metric": c["label"],
                "score": c["score"],
                "status": status,
                "cause": cause,
                "suggestion": suggestion,
            })
        weak = min(comps.items(), key=lambda kv: kv[1]["score"])
        summary = (
            f"当前综合性能评分 {score['total']}（{score['grade']} 级）。"
            f"最薄弱的环节是「{weak[1]['label']}」（{weak[1]['score']} 分），"
            f"建议优先处理。整体 Web 层与缓存层表现优秀，数据库与 PHP 运行时存在优化空间。"
        )
        return {"summary": summary, "items": items}

    # -- L4 optimizations -------------------------------------------------

    def _optimization_list(self) -> List[Dict[str, Any]]:
        applied = self.applied_optimizations
        return [
            {
                "id": "worker_scale",
                "title": "扩容 PHP Worker 连接池",
                "desc": "将 worker 数量从 8 提升至 12，连接上限 800 → 1200，缓解高峰排队。",
                "applied": "worker_scale" in applied,
                "effect": "排队数预计下降 40%，P95 降低约 15%。",
            },
            {
                "id": "opcache_up",
                "title": "提升 OPcache 内存上限",
                "desc": "OPcache 内存 64MB → 256MB，提升脚本命中率，降低 PHP 编译开销。",
                "applied": "opcache_up" in applied,
                "effect": "PHP 平均执行时间预计下降 20%。",
            },
            {
                "id": "cache_warm",
                "title": "LSCache 全站缓存预热",
                "desc": "对热门 URL 执行主动缓存预热，提升首访命中率。",
                "applied": "cache_warm" in applied,
                "effect": "命中率预计提升至 99%+。",
            },
            {
                "id": "db_index",
                "title": "数据库慢查询自动加索引",
                "desc": "为 wp_postmeta / wp_options 高频查询字段创建复合索引。",
                "applied": "db_index" in applied,
                "effect": "慢查询数量预计下降 50%。",
            },
            {
                "id": "heartbeat_tune",
                "title": "限制 WordPress Heartbeat 频率",
                "desc": "将后台心跳从 15s 调整为 60s，降低 admin-ajax 占用。",
                "applied": "heartbeat_tune" in applied,
                "effect": "worker 占用下降，后台更流畅。",
            },
        ]

    def _apply_optimization(self, action: str) -> Dict[str, Any]:
        s = self.state
        if action == "worker_scale":
            s["worker_total"] = min(20, s["worker_total"] + 4)
            s["worker_conns"] = 1200
            s["p95_ms"] = _clamp(s["p95_ms"] * 0.85, 80, 1500)
        elif action == "opcache_up":
            s["opcache_total_mb"] = 256.0
            s["php_avg_ms"] = _clamp(s["php_avg_ms"] * 0.8, 10, 600)
        elif action == "cache_warm":
            s["cache_hit"] = _clamp(99.2, 0, 100)
            s["redis_hit"] = _clamp(max(s["redis_hit"], 98), 0, 100)
        elif action == "db_index":
            s["db_avg_ms"] = _clamp(s["db_avg_ms"] * 0.6, 4, 200)
            s["db_qps"] = _clamp(s["db_qps"] * 0.9, 20, 900)
        elif action == "heartbeat_tune":
            s["php_avg_ms"] = _clamp(s["php_avg_ms"] * 0.92, 10, 600)
        else:
            return {"ok": False, "message": f"未知优化项: {action}"}
        self.applied_optimizations[action] = _now()
        self._add_event()
        return {
            "ok": True,
            "action": action,
            "message": "已应用优化，指标正在收敛。",
            "applied_at": _now(),
            "score": self._score(),
        }


# Module-level singleton so polls are coherent and optimizations persist.
_simulator = WPRuntimeSimulator()


def get_runtime_snapshot(db=None) -> Dict[str, Any]:
    return _simulator.snapshot(db)


def apply_optimization(action: str) -> Dict[str, Any]:
    return _simulator.optimize(action)
