<?php
/*
Plugin Name: Sanguo Panel Hide Login
Description: Hides wp-admin and wp-login.php behind a custom slug. Generated by Sanguo Panel.
*/

if (!defined('ABSPATH')) exit;

add_action('init', function() {
    $custom_slug = 'denglu';
    $secret_key = 'ff07cfb1041d8ba2746f30b88b10630e';
    $request_uri = $_SERVER['REQUEST_URI'];
    $path = trim(parse_url($request_uri, PHP_URL_PATH), '/');
    
    // 1. If accessing the custom slug, set a cookie and redirect to wp-login.php
    if ($path === $custom_slug) {
        setcookie('sanguo_hide_login', $secret_key, time() + 3600 * 24, '/');
        wp_redirect(site_url('wp-login.php'));
        exit;
    }
    
    // 2. Block direct access to wp-login.php and wp-admin if not logged in and no cookie
    if ((strpos($request_uri, 'wp-login.php') !== false || strpos($request_uri, 'wp-admin') !== false) 
        && !isset($_COOKIE['sanguo_hide_login']) 
        && !is_user_logged_in()) {
        
        // Allow access to admin-ajax.php and admin-post.php which are often used by themes/plugins
        if (strpos($request_uri, 'admin-ajax.php') !== false || strpos($request_uri, 'admin-post.php') !== false) {
            return;
        }
        
        status_header(403);
        wp_die('Access Denied. Please use your secret login URL.', '403 Forbidden', ['response' => 403]);
    }
}, 1);

// Optional: Filter login URL to use the custom slug instead of wp-login.php
add_filter('login_url', function($login_url, $redirect, $force_reauth) use ($custom_slug) {
    return home_url('/' . $custom_slug);
}, 10, 3);
?>